export const statusColumnSx = {
  root: {
    width: 350,
    flex: "0 0 350px",
    background: "var(--panel)",
    color: "var(--text)",
    border: "1px solid var(--border)",
    borderRadius: "14px",
    p: 1.5,
    boxShadow: "var(--shadow)",
  },
  headerPill: (color) => ({
    width: "100%",
    height: 42,
    display: "flex",
    alignItems: "center",
    gap: 1.25,
    px: 1.75,
    borderRadius: "var(--radius-sm)",
    border: `1.5px solid ${color}`,
    mb: 1.5,
    color,
  }),
  headerIcon: { width: 18, display: "inline-flex", justifyContent: "center", alignItems: "center" },
  headerTitle: { fontSize: 16, fontWeight: 800 },
  addBtn: (color) => ({
    ml: "auto",
    minWidth: 0,
    color,
    p: "4px 8px",
    borderRadius: "8px",
    "&:hover": { background: "var(--primary-weak)" },
  }),
  list: { mt: 1.25, display: "grid", gap: 1.5 },
  emptyWrap: { display: "grid", gap: 1 },
  emptyLabel: (color) => ({ fontSize: 12, display: "flex", alignItems: "center", gap: 0.75, color }),
  emptyBox: (borderColor, gradient) => ({
    border: `2px dashed ${borderColor}`,
    borderRadius: "14px",
    p: 2,
    minHeight: 140,
    display: "grid",
    placeItems: "center",
    textAlign: "center",
    background: gradient,
  }),
  emptyIcon: (color) => ({ mb: 0.75, color }),
  emptyTitle: (color) => ({ fontSize: 18, fontWeight: 900, color }),
  emptyHint: { mt: 0.75, fontSize: 12, color: "var(--muted)" },
};
