const STATUS_COLORS = {
  wishlist: "#9b5cf6",
  applied: "#3b82f6",
  interviewing: "#f59e0b",
  offer: "#22c55e",
};

export const getStatusColor = (status) =>
  STATUS_COLORS[status.toLowerCase().replace(/\s+/g, "")] || "var(--text)";

const rowBase = {
  display: "grid",
  gridTemplateColumns: {
    xs: "44px 1.8fr 70px 46px",
    md: "44px 1.6fr 1.5fr 90px 52px",
  },
  gap: 1.25,
  alignItems: "center",
  px: 1.25,
  py: 1.25,
  borderTop: "1px solid var(--border)",
  position: "relative",
  minWidth: 0,
};

export const listViewSx = {
  root: { width: "100%", maxWidth: 1600, minHeight: 0, color: "var(--text)" },
  section: { mb: 1.25 },
  sectionHeader: {
    width: "100%",
    justifyContent: "flex-start",
    textTransform: "none",
    color: "inherit",
    px: 0.75,
    py: 1.25,
    gap: 1.25,
    fontWeight: 800,
  },
  chevron: (collapsed) => ({ opacity: 0.8, transform: collapsed ? "rotate(-90deg)" : "rotate(0deg)", transition: "transform 120ms ease" }),
  sectionTitle: (statusColor) => ({ fontSize: 14, fontWeight: 900, color: statusColor }),
  sectionCount: { fontSize: 12, color: "var(--muted)", fontWeight: 800 },
  table: { border: "1px solid var(--border)", borderRadius: "var(--radius)", overflow: "visible", bgcolor: "var(--panel)", boxShadow: "var(--shadow)", color: "var(--text)" },
  headRow: { ...rowBase, bgcolor: "var(--panel-2)", color: "var(--muted)", fontWeight: 800, cursor: "default", borderTop: "none" },
  checkCell: { display: "flex", justifyContent: "center" },
  checkbox: {
    color: "var(--muted)",
    "&.Mui-checked": { color: "var(--primary)" },
    "&.MuiCheckbox-indeterminate": { color: "var(--primary)" },
  },
  headText: { fontSize: 13, fontWeight: 800 },
  headTextTags: { fontSize: 13, fontWeight: 800, display: { xs: "none", md: "block" } },
  headTextDate: { fontSize: 13, fontWeight: 800, textAlign: "right" },
  empty: { p: 1.75, color: "var(--muted)", fontWeight: 800 },
  row: (checked, index) => ({
    ...rowBase,
    borderTop: index === 0 ? "none" : rowBase.borderTop,
    bgcolor: checked ? "var(--primary-weak)" : "transparent",
    color: "var(--text)",
    cursor: "pointer",
    "&:hover": { bgcolor: "color-mix(in srgb, var(--panel) 92%, var(--text) 8%)" },
  }),
  titleRow: { display: "flex", alignItems: "baseline", gap: 1.25, minWidth: 0, overflow: "hidden" },
  company: { fontWeight: 900, fontSize: 13, whiteSpace: "nowrap", color: "var(--text)" },
  role: { fontWeight: 700, fontSize: 12, color: "var(--muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  meta: { fontSize: 12, color: "var(--muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  tagsWrap: { display: { xs: "none", md: "flex" }, flexWrap: "wrap", gap: 0.75 },
  tag: (statusColor) => ({ fontSize: 11, fontWeight: 900, px: 1.25, py: 0.625, borderRadius: 999, color: statusColor, bgcolor: `color-mix(in srgb, ${statusColor} 14%, transparent)`, border: `1px solid color-mix(in srgb, ${statusColor} 40%, transparent)` }),
  tagMore: (statusColor) => ({ fontSize: 11, fontWeight: 900, px: 1.25, py: 0.625, borderRadius: 999, opacity: 0.75, color: statusColor, bgcolor: `color-mix(in srgb, ${statusColor} 14%, transparent)`, border: `1px solid color-mix(in srgb, ${statusColor} 40%, transparent)` }),
  date: { fontSize: 12, color: "var(--muted)", textAlign: "right", whiteSpace: "nowrap" },
  kebabBtn: { minWidth: 34, width: 34, height: 34, borderRadius: "12px", border: "1px solid var(--border)", color: "var(--text)", p: 0 },
  rowMenu: { position: "absolute", right: 0, top: 42, zIndex: 50, width: 190, borderRadius: "12px", bgcolor: "var(--panel)", border: "1px solid var(--border)", boxShadow: "var(--shadow)", p: 1, color: "var(--text)" },
  menuInner: { display: "flex", flexDirection: "column", gap: 0.75 },
  menuItem: { justifyContent: "flex-start", textTransform: "none", borderRadius: "10px", color: "var(--text)", fontWeight: 800, gap: 1, py: 1 },
  dangerMenuItem: { justifyContent: "flex-start", textTransform: "none", borderRadius: "10px", color: "#b00020", fontWeight: 800, gap: 1, py: 1, background: "#fff5f5", border: "1px solid #ffd7d7" },
  moveMenu: { border: "1px solid var(--border)", borderRadius: "10px", p: 0.5, display: "grid", gap: 0.25 },
  moveItem: { justifyContent: "flex-start", textTransform: "none", color: "var(--text)", borderRadius: "8px", fontWeight: 700, py: 0.75, px: 1 },
  bulkBar: { position: "sticky", bottom: 12, zIndex: 40, mt: 1.5, mx: "auto", width: "min(980px, 100%)", borderRadius: "var(--radius)", border: "1px solid var(--border)", bgcolor: "var(--panel)", boxShadow: "var(--shadow)", display: "flex", alignItems: "center", justifyContent: "space-between", gap: 1.5, p: 1.5, flexWrap: "wrap", color: "var(--text)" },
  bulkLeft: { display: "flex", alignItems: "center", gap: 1.25 },
  bulkRight: { display: "flex", alignItems: "center", gap: 1.25 },
  ghostBtn: { textTransform: "none", border: "1px solid var(--border)", color: "inherit", px: 1.25, py: 1, borderRadius: "var(--radius-sm)", fontWeight: 800 },
  bulkDangerBtn: {
    textTransform: "none",
    borderRadius: "var(--radius-sm)",
    px: 1.5,
    py: 1.125,
    border: "1px solid var(--border)",
    bgcolor: "#ffffff",
    color: "#b00020",
    fontWeight: 900,
    "& .MuiButton-startIcon": { color: "#b00020" },
  },
  bulkMoveMenu: { position: "absolute", bottom: 52, left: 0, zIndex: 60, width: { xs: 200, md: 220 }, p: 1, borderRadius: "var(--radius)", border: "1px solid var(--border)", bgcolor: "var(--panel)", boxShadow: "var(--shadow)" },
  bulkMoveItem: { justifyContent: "flex-start", textTransform: "none", border: "1px solid transparent", color: "inherit", py: 1.25, px: 1.5, borderRadius: "var(--radius-sm)", fontWeight: 900 },
};
