export const topbarSx = {
  root: {
    position: "sticky",
    top: 0,
    zIndex: 50,
    background: "var(--topbar-bg)",
    borderBottom: "1px solid var(--border)",
    p: "16px 22px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 2,
  },
  title: { fontSize: 18, fontWeight: 950, color: "var(--text)" },
  right: { display: "flex", alignItems: "center", gap: 1.25 },
  ghostBtn: {
    width: 45,
    height: 45,
    border: "1px solid var(--border)",
    borderRadius: "10px",
    color: "#6b7280",
  },
  searchBox: {
    width: "min(250px, 45vw)",
    height: 45,
    display: "flex",
    alignItems: "center",
    gap: 1.25,
    px: 1.5,
    border: "1px solid var(--border)",
    borderRadius: "10px",
    background: "var(--topbar-bg)",
  },
  searchIcon: { fontSize: 18, color: "#9ca3af" },
  searchInput: {
    width: "100%",
    fontSize: 14,
    color: "var(--text)",
    "& input::placeholder": { color: "#9ca3af", opacity: 1 },
  },
};
