export const toastSx = {
  container: {
    position: "fixed",
    bottom: 20,
    right: 20,
    display: "flex",
    flexDirection: "column",
    gap: 1.75,
    zIndex: 999999,
  },
  card: (color) => ({
    width: 360,
    background: "var(--panel)",
    color: "var(--text)",
    borderRadius: "var(--radius)",
    p: 2,
    boxShadow: "var(--shadow)",
    border: "1px solid var(--border)",
    borderLeft: `6px solid ${color}`,
  }),
  content: { display: "flex", alignItems: "center", gap: 1.5 },
  iconWrap: (color) => ({
    width: 38,
    height: 38,
    borderRadius: "999px",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: color,
    flexShrink: 0,
  }),
  text: { flex: 1, minWidth: 0 },
  title: { fontWeight: 900, fontSize: 16, lineHeight: 1.1 },
  message: { fontSize: 13, color: "var(--muted)", mt: 0.5 },
  closeBtn: {
    minWidth: 0,
    p: "4px 8px",
    borderRadius: "10px",
    color: "var(--muted)",
    "&:hover": { background: "var(--panel-2)", color: "var(--text)" },
  },
};
