export const profileMenuSx = {
  wrap: { position: "relative" },
  trigger: {
    display: "flex",
    alignItems: "center",
    gap: 1.25,
    border: "1px solid var(--border)",
    background: "var(--panel)",
    borderRadius: "14px",
    p: "8px 10px",
    textTransform: "none",
    color: "var(--text)",
    minWidth: 0,
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: "10px",
    objectFit: "cover",
    border: "1px solid rgba(0,0,0,0.08)",
  },
  name: {
    fontWeight: 850,
    fontSize: 14,
    color: "var(--text)",
    maxWidth: 160,
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  menu: {
    position: "absolute",
    right: 0,
    top: "calc(100% + 10px)",
    width: 220,
    background: "var(--panel)",
    border: "1px solid var(--border)",
    borderRadius: "14px",
    boxShadow: "0 14px 40px rgba(0,0,0,0.14)",
    p: 1,
    zIndex: 9999,
  },
  item: {
    width: "100%",
    justifyContent: "flex-start",
    gap: 1,
    textTransform: "none",
    borderRadius: "12px",
    color: "var(--text)",
    fontWeight: 800,
  },
  dangerItem: {
    width: "100%",
    justifyContent: "flex-start",
    gap: 1,
    textTransform: "none",
    borderRadius: "12px",
    color: "#b00020",
    fontWeight: 800,
    "&:hover": { background: "rgba(176,0,32,0.08)" },
  },
};
