export const authPageSx = {
  root: {
    minHeight: "100vh",
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "var(--bg)",
    p: 2,
  },
  card: {
    width: "min(420px, 100%)",
    background: "var(--panel)",
    border: "1px solid var(--border)",
    borderRadius: "16px",
    boxShadow: "var(--shadow)",
    p: 3,
    display: "flex",
    flexDirection: "column",
    gap: 1.5,
  },
  title: {
    fontSize: 22,
    fontWeight: 900,
    color: "var(--text)",
    lineHeight: 1.2,
  },
  subtitle: {
    fontSize: 14,
    color: "var(--muted)",
    mb: 0.5,
  },
  alert: {
    borderRadius: "10px",
    fontSize: 13,
  },
  field: {
    display: "flex",
    flexDirection: "column",
    gap: 0.75,
  },
  label: {
    fontSize: 13,
    color: "var(--muted)",
  },
  input: {
    "& .MuiOutlinedInput-root": {
      borderRadius: "10px",
      color: "var(--text)",
      background: "var(--panel)",
      "& fieldset": { borderColor: "var(--border)" },
      "&:hover fieldset": { borderColor: "var(--border)" },
    },
    "& .MuiInputBase-input::placeholder": { color: "var(--muted)", opacity: 0.8 },
  },
  submitBtn: {
    textTransform: "none",
    background: "var(--primary)",
    border: "1px solid var(--primary)",
    color: "#fff",
    borderRadius: "10px",
    px: 1.75,
    py: 1.25,
    fontWeight: 700,
    fontSize: 15,
    mt: 0.5,
    "&:hover": { opacity: 0.9 },
    "&:disabled": { opacity: 0.6, color: "#fff" },
  },
  footer: {
    fontSize: 13,
    color: "var(--muted)",
    textAlign: "center",
    mt: 0.5,
  },
  link: {
    color: "var(--primary)",
    textDecoration: "none",
    fontWeight: 700,
    "&:hover": { textDecoration: "underline" },
  },
};
