export const sidebarSx = {
  root: (collapsed) => ({
    background: "var(--panel)",
    color: "var(--text)",
    borderRight: "1px solid var(--border)",
    p: collapsed ? "18px 10px" : "18px 16px",
    display: "flex",
    flexDirection: "column",
    height: "100%",
    width: collapsed ? 76 : 240,
    transition: "width 180ms ease, padding 180ms ease",
    overflowX: "hidden",
  }),
  brand: (collapsed) => ({
    display: "flex",
    alignItems: "center",
    p: "6px",
    justifyContent: collapsed ? "center" : "flex-start",
  }),
  brandImage: (collapsed) => ({
    width: collapsed ? 44 : 160,
    height: "auto",
    objectFit: "contain",
    transition: "width 180ms ease",
  }),
  nav: { mt: 1.25, display: "grid", gap: 0.75, px: 0.75 },
  navItem: (active, collapsed) => ({
    position: "relative",
    justifyContent: collapsed ? "center" : "flex-start",
    gap: collapsed ? 0 : 1.25,
    width: "100%",
    maxWidth: "100%",
    minWidth: 0,
    px: collapsed ? 1.25 : 1.5,
    py: 1.25,
    boxSizing: "border-box",
    borderRadius: "12px",
    textTransform: "none",
    color: active ? "var(--primary)" : "var(--text)",
    border: "1px solid transparent",
    background: active
      ? "color-mix(in srgb, var(--primary) 12%, transparent)"
      : "transparent",
    fontWeight: 600,
    "&:hover": {
      borderColor: "color-mix(in srgb, var(--border) 60%, transparent)",
      background: "color-mix(in srgb, var(--text) 4%, transparent)",
    },
    "&::before": active
      ? {
          content: '""',
          position: "absolute",
          left: collapsed ? "4px" : "6px",
          top: "8px",
          bottom: "8px",
          width: "3px",
          borderRadius: "999px",
          background: "var(--primary)",
        }
      : undefined,
  }),
  navIcon: { width: 18, display: "inline-flex", alignItems: "center", justifyContent: "center" },
  footerWrap: { mt: "auto", px: 0.75 },
  footerRow: (collapsed) => ({
    display: "flex",
    flexDirection: collapsed ? "column" : "row",
    alignItems: "center",
    justifyContent: collapsed ? "center" : "space-between",
    gap: 1.25,
    p: "10px 6px",
  }),
  collapseBtn: {
    minWidth: 36,
    width: 36,
    height: 36,
    borderRadius: "12px",
    color: "var(--muted)",
  },
};
