export const addJobModalSx = {
  overlay: {
    position: "fixed",
    inset: 0,
    background: "rgba(0,0,0,0.35)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    p: 2,
    zIndex: 999,
  },
  card: {
    width: "min(520px, 100%)",
    background: "var(--panel)",
    border: "1px solid var(--border)",
    borderRadius: "16px",
    p: 2.25,
    boxShadow: "var(--shadow)",
    display: "grid",
    gap: 1.25,
  },
  header: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: 1.5, mb: 0.5 },
  title: { fontSize: 18, fontWeight: 900, color: "var(--text)" },
  closeBtn: { minWidth: 36, width: 36, height: 36, borderRadius: "10px", border: "1px solid var(--border)", color: "var(--text)" },
  field: { display: "grid", gap: 0.75 },
  label: { fontSize: 13, color: "var(--muted)" },
  grid2: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 1.25 },
  input: {
    "& .MuiOutlinedInput-root": {
      borderRadius: "10px",
      color: "var(--text)",
      background: "var(--panel)",
      "& fieldset": { borderColor: "var(--border)" },
      "&:hover fieldset": { borderColor: "var(--border)" },
    },
    "& .MuiInputBase-input::placeholder": { color: "var(--muted)", opacity: 0.8 },
  },
  actions: { display: "flex", gap: 1.25, justifyContent: "flex-end", mt: 0.75 },
  primaryBtn: {
    textTransform: "none",
    border: "1px solid var(--primary)",
    background: "var(--primary)",
    color: "#fff",
    borderRadius: "10px",
    px: 1.75,
    py: 1.25,
    fontWeight: 700,
  },
  secondaryBtn: {
    textTransform: "none",
    border: "1px solid var(--border)",
    background: "var(--panel-2)",
    color: "var(--text)",
    borderRadius: "10px",
    px: 1.75,
    py: 1.25,
    fontWeight: 700,
  },
};
