export const jobCardSx = {
  card: (cardTheme) => ({
    width: "100%",
    minWidth: 0,
    overflow: "hidden",
    borderRadius: "16px",
    p: 1.75,
    border: "1px solid var(--border)",
    boxShadow: "var(--shadow)",
    display: "grid",
    gap: 1.5,
    cursor: "pointer",
    background: cardTheme.background,
    borderColor: cardTheme.borderColor,
  }),
  topRow: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: 1.25, minWidth: 0 },
  brandRow: { display: "flex", alignItems: "center", gap: 1.25, minWidth: 0, flex: 1 },
  logoCircle: (logoBg) => ({
    width: 44,
    height: 44,
    minWidth: 44,
    borderRadius: "12px",
    display: "grid",
    placeItems: "center",
    fontWeight: 900,
    fontSize: 13,
    color: "var(--text)",
    border: "1px solid var(--border)",
    boxShadow: "0 4px 12px rgba(0,0,0,0.08)",
    background: logoBg,
    overflow: "hidden",
  }),
  companyName: { fontWeight: 900, color: "var(--text)", lineHeight: 1.1, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  subtitle: { mt: 0.25, fontSize: 13, color: "var(--muted)", whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  kebabBtn: { minWidth: 34, width: 34, height: 34, borderRadius: "12px", border: "1px solid var(--border)", color: "var(--text)", p: 0 },
  menuBox: (pos) => ({
    position: "fixed",
    width: 190,
    borderRadius: "12px",
    p: 1,
    zIndex: 999999,
    background: "var(--panel)",
    border: "1px solid var(--border)",
    boxShadow: "var(--shadow)",
    top: pos.top,
    left: pos.left,
  }),
  menuInner: { display: "flex", flexDirection: "column", gap: 0.75 },
  menuItem: { justifyContent: "flex-start", textTransform: "none", borderRadius: "10px", color: "var(--text)", fontWeight: 800, gap: 1 },
  dangerItem: { justifyContent: "flex-start", textTransform: "none", borderRadius: "10px", color: "#b00020", fontWeight: 800, gap: 1, background: "#fff5f5", border: "1px solid #ffd7d7" },
  tagsRow: { display: "flex", flexWrap: "wrap", gap: 1 },
  tagPill: { fontSize: 13, p: "6px 10px", borderRadius: "999px", fontWeight: 600, background: "color-mix(in srgb, var(--panel) 80%, transparent)", border: "1px solid var(--border)", color: "var(--text)" },
  footerRow: { display: "flex", alignItems: "center", justifyContent: "space-between" },
  metaRow: { display: "flex", alignItems: "center", gap: 1, color: "var(--muted)" },
  metaText: { fontSize: 13, opacity: 0.9 },
  infoBtn: { minWidth: 26, width: 26, height: 26, borderRadius: "999px", p: 0, border: "1px solid var(--border)", color: "var(--text)" },
  modalOverlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.35)", display: "grid", placeItems: "center", zIndex: 1000000, p: 2 },
  modalBox: { width: "min(420px,100%)", borderRadius: "16px", p: 2, background: "var(--panel)", border: "1px solid var(--border)", boxShadow: "var(--shadow)" },
  modalTitle: { fontSize: 18, fontWeight: 900, color: "var(--text)", mb: 1.5 },
  field: { display: "grid", gap: 0.75, mb: 1.5 },
  label: { fontSize: 13, fontWeight: 900, color: "var(--text)" },
  input: (bg) => ({
    "& .MuiOutlinedInput-root": {
      borderRadius: "12px",
      background: bg,
      color: "var(--text)",
      "& fieldset": { borderColor: "var(--border)" },
    },
  }),
  modalActions: { display: "flex", justifyContent: "flex-end", gap: 1.25, mt: 0.75 },
  btnGhost: { textTransform: "none", borderRadius: "12px", px: 1.5, py: 1.25, fontWeight: 900, border: "1px solid var(--border)", color: "var(--text)" },
  btnPrimary: { textTransform: "none", borderRadius: "12px", px: 1.75, py: 1.25, fontWeight: 900, border: "1px solid color-mix(in srgb, var(--primary) 70%, transparent)", background: "var(--primary)", color: "#fff" },
  btnDanger: { textTransform: "none", borderRadius: "12px", px: 1.75, py: 1.25, fontWeight: 900, background: "#b00020", border: "1px solid #b00020", color: "#fff" },
  confirmText: { mb: 0.75, fontSize: 14, color: "var(--text)", fontWeight: 600 },
  confirmSubtext: { mb: 2, fontSize: 13, color: "var(--muted)" },
  deleteHeader: { display: "flex", alignItems: "center", gap: 1, mb: 1.5 },
  deleteIcon: { width: 32, height: 32, borderRadius: "8px", background: "#fff0f0", display: "grid", placeItems: "center", color: "#b00020", border: "1px solid #ffd7d7" },
  moveCols: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 1.25, mb: 1.5 },
  moveRequired: { mb: 1.5, p: 1.25, borderRadius: "10px", border: "1px solid var(--border)", background: "color-mix(in srgb, var(--panel-2) 60%, transparent)" },
  moveRequiredLabel: { fontSize: 12, fontWeight: 700, color: "var(--muted)", mb: 1, textTransform: "uppercase", letterSpacing: "0.05em" },
  followUpBadge: { display: "flex", alignItems: "center", gap: 0.75, px: 1.25, py: 0.75, borderRadius: "8px", background: "#fff7ed", border: "1px solid #fed7aa", color: "#c2410c" },
  followUpText: { fontSize: 12, fontWeight: 700, color: "#c2410c" },
  reminderBadge: { display: "flex", alignItems: "center", gap: 0.75, px: 1.25, py: 0.75, borderRadius: "8px", background: "#eff6ff", border: "1px solid #bfdbfe", color: "#1d4ed8" },
  reminderText: { fontSize: 12, fontWeight: 700, color: "#1d4ed8" },
};
