export const jobDetailsDrawerSx = {
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.35)", zIndex: 9998 },
  drawer: {
    position: "fixed",
    top: 0,
    right: 0,
    height: "100vh",
    width: "min(420px, 92vw)",
    background: "var(--panel)",
    borderLeft: "1px solid var(--border)",
    zIndex: 9999,
    display: "flex",
    flexDirection: "column",
    boxShadow: "-18px 0 50px rgba(0,0,0,0.18)",
  },
  header: { p: "14px 14px 10px", borderBottom: "1px solid var(--border)", display: "flex", justifyContent: "space-between", gap: 1.25 },
  companyRow: { display: "flex", alignItems: "center", gap: 1.5 },
  companyInitial: { width: 44, height: 44, borderRadius: "14px", display: "grid", placeItems: "center", fontWeight: 950, background: "rgba(0,0,0,0.05)", border: "1px solid var(--border)" },
  titleBlock: { display: "grid", gap: 0.25 },
  jobTitle: { fontWeight: 950, color: "var(--text)" },
  companyName: { color: "var(--muted)", fontSize: 13 },
  statusPill: (statusColor) => ({
    mt: 0.5,
    fontWeight: 700,
    color: statusColor,
    border: `1px solid color-mix(in srgb, ${statusColor} 40%, transparent)`,
    background: `color-mix(in srgb, ${statusColor} 14%, transparent)`,
  }),
  closeBtn: { minWidth: 36, width: 36, height: 36, borderRadius: "12px", border: "1px solid var(--border)", color: "var(--text)" },
  body: { p: 1.75, overflow: "auto", display: "grid", gap: 1.75 },
  section: { border: "1px solid var(--border)", borderRadius: "16px", background: "rgba(0,0,0,0.02)", overflow: "hidden" },
  sectionTitle: { p: "10px 12px", fontWeight: 950, borderBottom: "1px solid var(--border)" },
  sectionBody: { p: 1.5, display: "grid", gap: 1.25 },
  row: { display: "flex", justifyContent: "space-between", gap: 1.5 },
  rowLabel: { color: "var(--muted)", fontSize: 13, fontWeight: 800, flex: "0 0 90px" },
  rowValue: {
    color: "var(--text)",
    fontSize: 13,
    fontWeight: 700,
    minWidth: 0,
    textAlign: "right",
    overflow: "hidden",
    textOverflow: "ellipsis",
    "& a": { color: "var(--primary)", textDecoration: "none" },
  },
  tags: { display: "flex", flexWrap: "wrap", gap: 1 },
  tag: (statusColor) => ({
    fontWeight: 700,
    color: statusColor,
    border: `1px solid color-mix(in srgb, ${statusColor} 40%, transparent)`,
    background: `color-mix(in srgb, ${statusColor} 14%, transparent)`,
  }),
  muted: { color: "var(--muted)", fontSize: 13 },
  textarea: {
    "& .MuiOutlinedInput-root": {
      borderRadius: "12px",
      borderColor: "var(--border)",
      color: "var(--text)",
      background: "var(--panel)",
      "& fieldset": { borderColor: "var(--border)" },
    },
  },
  noteHint: { color: "var(--muted)", fontSize: 12 },
  footer: { p: "12px 14px", borderTop: "1px solid var(--border)", display: "flex", justifyContent: "flex-end" },
  primaryBtn: {
    textTransform: "none",
    border: "1px solid color-mix(in srgb, var(--primary) 70%, transparent)",
    background: "var(--primary)",
    color: "#fff",
    borderRadius: "12px",
    px: 1.75,
    py: 1.25,
    fontWeight: 900,
  },
};
